source/site/pricing-new.ejs, themes/searchtap/source/css/demo.css
=> new pricing page

source/site/pricing-new.ejs, themes/searchtap/source/css/demo.css
price font changes in mobile view
=> price font changes in mobile view

themes/searchtap/source/css/custom.css
=> custom css updated

source/_data/blog.json
=> search-experience url change

source/_data/blog.json
tips-for-enhancing-mobile-search-experience.ejs
=> tips-for-enhancing-mobile-search-experience.ejs

source/_data/blog.json, source/site/blog/redesigning-search.ejs, source/site/blog/tips-for-enhancing-mobile-search-experience.ejs
=> blog content changes

source/site/greenhonchos.ejs
=> blog text change

source/site/greenhonchos.ejs
=> greenhonchos images updated

source/site/shopify-plus.ejs, themes/searchtap/layout/_partial/footer-nav.ejs, themes/searchtap/layout/_partial/header-nav.ejs, themes/searchtap/layout/_partial/mobile-nav.ejs
=> replace shopify gold to plus

themes/searchtap/layout/_partial/mobile-nav.ejs
=> footer changes

themes/searchtap/layout/_partial/footer-nav.ejs
=> footer link change

themes/searchtap/source/css/demo.css
=> blog css changes

source/site/searchtap-agency-partners.ejs
=> blog banner css

source/site/portfolio/huft.ejs, source/site/portfolio/libertyshoes.ejs
=> portfolio responsiveness

source/site/portfolio/glen.ejs, source/site/portfolio/healthxp.ejs, source/site/portfolio/hipvan.ejs, source/site/portfolio/huft.ejs, source/site/portfolio/jewelmaze.ejs, source/site/portfolio/libertyshoes.ejs, source/site/portfolio/portronics.ejs, source/site/portfolio/propshop24.ejs, source/site/portfolio/srisri.ejs, source/site/portfolio/sugarcosmetics.ejs, source/site/portfolio/wforwomen.ejs, themes/searchtap/source/css/demo.css
=> button arrow added

source/site/portfolio/glen.ejs, source/site/portfolio/libertyshoes.ejs, source/site/portfolio/portronics.ejs, source/site/portfolio/propshop24.ejs, source/site/portfolio/srisri.ejs
=> Industry name changes

source/site/appmaker.ejs, source/site/portfolio.ejs, source/site/portfolio/healthxp.ejs, source/site/portfolio/hipvan.ejs, source/site/portfolio/huft.ejs, source/site/portfolio/jewelmaze.ejs, source/site/portfolio/propshop24.ejs, source/site/portfolio/wforwomen.ejs, themes/searchtap/source/css/demo.css
=> portfolio links

source/site/appmaker.ejs
=> appmaker text change

source/site/customized-search-UX-from-searchtap.ejs, themes/searchtap/source/css/demo.css
=> customized-search-UX

source/site/searchtap-facebook-grants.ejs, themes/searchtap/source/css/demo.css
searchtap-facebook-grants page created
=> searchtap-facebook-grants page created

source/site/searchtap-facebook-grants.ejs, themes/searchtap/source/css/demo.css, themes/searchtap/source/css/success-stories.css
searchtap-facebook-grants update
=> searchtap-facebook-grants update

themes/searchtap/source/css/demo.css
=> searchtap-facebook-grants css

themes/searchtap/source/css/success-stories.css
=> facebook-grants css

source/site/searchtap-facebook-grants.ejs
=> facebook-grants text change

source/site/searchtap-offer.ejs
=> searchtap offer page changes

source/site/blog/10-tips-for-a-better-mobile-search-ux.ejs
=> 10-tips-for-a-better-mobile-search-ux
